# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flutree < Formula
  desc "Manage Git worktrees for multi-package Flutter workflows."
  homepage "https://github.com/EndersonPro/flutree"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/EndersonPro/flutree/releases/download/v1.1.1/flutree-1.1.1-macos-arm64.tar.gz"
      sha256 "e25dee911d589e0b694397c6a23e72e5f8f68d587a344ff5cefa7a540dadae74"

      define_method(:install) do
        bin.install "flutree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/EndersonPro/flutree/releases/download/v1.1.1/flutree-1.1.1-linux-amd64.tar.gz"
      sha256 "4222156385ddccefcf02202fad3dd97e262353c1e4af1a79a34d2b6e919921b6"
      define_method(:install) do
        bin.install "flutree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EndersonPro/flutree/releases/download/v1.1.1/flutree-1.1.1-linux-arm64.tar.gz"
      sha256 "6a5e9f97fcfa30fc497a4c572ed195cdecda87393672eb2fe7498a948e88427d"
      define_method(:install) do
        bin.install "flutree"
      end
    end
  end

  test do
    system "#{bin}/flutree --version"
  end
end
